name: Mac no Python 2.7

on:
  push:
    branches:
      - remove_py27_ga
      # Can add additional branches if desired

jobs:
  pyomo-mac-tests:
    name: py${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8] # All available Python versions

    steps:
    - uses: actions/checkout@v1 # Checkout branch(es)
    - name: Set up Python ${{ matrix.python-version }} # Initialize Python version
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pyomo dependencies
      run: |
        echo "Install pre-dependencies for pyodbc..."
        brew update # Install pre-dependencies for pyodbc
        brew install bash gcc
        brew link --overwrite gcc
        brew install pkg-config
        brew install unixodbc
        brew install freetds # Now install Python modules
        python -m pip install --upgrade pip
        echo ""
        echo "Install Pyomo dependencies..."
        echo ""
        pip install cython numpy scipy ipython openpyxl sympy pyyaml pyodbc networkx xlrd pandas matplotlib dill seaborn pymysql pyro4 pint pathos
    - name: Install Pyomo and extensions
      run: |
        echo "Clone Pyomo-model-libraries..."
        python -m pip install --upgrade pip
        git clone --quiet https://github.com/Pyomo/pyomo-model-libraries.git
        echo ""
        echo "Install PyUtilib..."
        echo ""
        pip install --quiet git+https://github.com/PyUtilib/pyutilib
        echo ""
        echo "Install Pyomo..."
        echo ""
        python setup.py develop # Install Pyomo
        echo ""
        echo "Install extensions..."
        echo ""
        pyomo download-extensions # Get Pyomo extensions
        pyomo build-extensions
    - name: Run nightly, not fragile tests with test.pyomo
      run: |
        echo "Run test.pyomo..."
        python -m pip install --upgrade pip
        pip install nose
        KEY_JOB=1
        test.pyomo -v --cat="nightly" pyomo `pwd`/pyomo-model-libraries # Run nightly, stable tests
