name: continuous-integration/github/pr

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: mpi/${{ matrix.TARGET }}/py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        include:
        - os: ubuntu-latest
          TARGET: linux
    steps:
    - uses: actions/checkout@v2
    - name: setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy nose
        pip install --quiet git+https://github.com/PyUtilib/pyutilib
        conda install mpi4py
        python setup.py develop
    - name: Test with nose
      run: |
        mpirun -np 3 nosetests -v pyomo.contrib.pynumero.sparse.tests.test_mpi_block_vector.py pyomo.contrib.pynumero.sparse.tests.test_mpi_block_matrix.py
