name: parallel_tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy nose codecov coverage
        conda install mpi4py
        python setup.py develop
    - name: Test with nose
      run: |
        mpirun -np 3 nosetests -v --with-coverage --cover-xml --cover-package=pyomo.contrib.pynumero.sparse pyomo.contrib.pynumero.sparse.tests.test_mpi_block_vector.py pyomo.contrib.pynumero.sparse.tests.test_mpi_block_matrix.py
        coverage report -m
