name: GitHub Branch CI (win)

on:
  push:
    branches-ignore:
      - master

jobs:
  pyomo-tests:
    name: win/py${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false # This flag causes all of the matrix to continue to run, even if one matrix option fails
      matrix:
        python-version: [3.7] 
    steps:
    - uses: actions/checkout@v2

    - name: Conda package cache
      id: conda-cache
      uses: actions/cache@v1
      with:
        path: conda-cache
        key: conda-${{runner.os}}-${{matrix.python-version}}

    - name: Download cache
      id: download-cache
      uses: actions/cache@v1
      with:
        path: download-cache
        key: download-${{runner.os}}

    - name: Set up Python ${{ matrix.python-version }} with Miniconda
      uses: goanpeca/setup-miniconda@v1 # Using an action created by user goanpeca to set up different Python Miniconda environments
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install Pyomo dependencies
      shell: pwsh
      run: |
        $env:PYTHONWARNINGS="ignore::UserWarning"
        Write-Host ("Current Enviroment variables: ")
        gci env:Path | Sort Name
        Write-Host ("")
        Write-Host ("Update conda, then force it to NOT update itself again...")
        Write-Host ("")
        Invoke-Expression "conda config --set always_yes yes"
        Invoke-Expression "conda config --set auto_update_conda false"
        Invoke-Expression "conda config --remove-key pkgs_dirs"
        Invoke-Expression "conda config --append pkgs_dirs $env:GITHUB_WORKSPACE\conda-cache"
        conda info
        conda config --show-sources
        conda list --show-channel-urls
        Write-Host ("")
        Write-Host ("Setting Conda Env Vars... ")
        Write-Host ("")
        $env:CONDA_INSTALL = "conda install -q -y "
        $env:ANACONDA = "$env:CONDA_INSTALL -c anaconda "
        $env:CONDAFORGE = "$env:CONDA_INSTALL -c conda-forge --no-update-deps "
        $env:USING_MINICONDA = 1
        $env:MINICONDA_EXTRAS="numpy scipy ipython openpyxl sympy pyodbc"
        $env:MINICONDA_EXTRAS+=" pyyaml networkx xlrd pandas matplotlib"
        $env:MINICONDA_EXTRAS+=" dill seaborn"
        $env:ADDITIONAL_CF_PKGS="setuptools pip coverage sphinx_rtd_theme"
        $env:ADDITIONAL_CF_PKGS+=" pymysql pyro4 pint pathos $env:MINICONDA_EXTRAS"
        $env:ADDITIONAL_CF_PKGS+=" glpk ipopt"
        Invoke-Expression "$env:CONDAFORGE $env:ADDITIONAL_CF_PKGS"
        Write-Host ("")
        Write-Host ("Try to install CPLEX...")
        Write-Host ("")
        try
        {
            Invoke-Expression "$env:CONDAFORGE -c ibmdecisionoptimization cplex=12.10"
        }
        catch
        {
            Write-Host ("##########################################################################")
            Write-Host ("WARNING: CPLEX Community Edition is not available for Python ${{ matrix.python-version }}")
            Write-Host ("##########################################################################")
            conda deactivate
            conda activate test
        }
        Write-Host ("")
        Write-Host ("Installing GAMS")
        Write-Host ("")
        if ( -not (Test-Path "$env:GITHUB_WORKSPACE\download-cache\windows_x64_64.exe")) {
            New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\download-cache"
            Invoke-WebRequest -Uri 'https://d37drm4t2jghv5.cloudfront.net/distributions/29.1.0/windows/windows_x64_64.exe' -OutFile "$env:GITHUB_WORKSPACE\download-cache\windows_x64_64.exe"
        }
        Start-Process -FilePath "$env:GITHUB_WORKSPACE\download-cache\windows_x64_64.exe" -ArgumentList '/SP- /VERYSILENT /NORESTART /DIR=.\gams /NOICONS' -Wait
        cd gams\apifiles\Python\
        if(${{matrix.python-version}} -eq 2.7) {
          cd api
          python setup.py install
        }elseif(${{matrix.python-version}} -eq 3.6) {
          cd api_36
          python setup.py install
        }elseif(${{matrix.python-version}} -eq 3.7) {
          cd api_37
          python setup.py install
        }else { 
          Write-Host ("########################################################################")
          Write-Host ("WARNING: Python ${{matrix.python-version}}: GAMS Bindings not supported.")
          Write-Host ("########################################################################")
        }
        Write-Host ("")
        Write-Host ("Conda package environment")
        Write-Host ("")
        conda list --show-channel-urls
        Write-Host ("")
        Write-Host ("New Shell Environment: ")
        gci env: | Sort Name

    - name: Install Pyomo and PyUtilib
      shell: pwsh
      run: |
        $env:PYTHONWARNINGS="ignore::UserWarning"
        Write-Host ("")
        Write-Host ("Clone model library and install PyUtilib...")
        Write-Host ("")
        git clone --quiet https://github.com/Pyomo/pyomo-model-libraries.git
        git clone --quiet https://github.com/PyUtilib/pyutilib.git
        cd pyutilib
        try
        {
            python3 setup.py develop
        }
        catch
        {
            python setup.py develop
        }
        cd ..
        Write-Host ("")
        Write-Host ("Install Pyomo...")
        Write-Host ("")
        try
        {
            python3 setup.py develop
        }
        catch
        {
            python setup.py develop
        }

    - name: Download and install extensions
      shell: pwsh
      run: |
        Write-Host ("")
        Write-Host "Pyomo download-extensions"
        Write-Host ("")
        Invoke-Expression "pyomo download-extensions"
        Write-Host ("")
        Write-Host "Pyomo build-extensions"
        Write-Host ("")
        Invoke-Expression "pyomo build-extensions"

    - name: Run nightly tests with test.pyomo
      shell: pwsh
      run: |
        $env:PYTHONWARNINGS="ignore::UserWarning"
        Write-Host "Setup and run nosetests"
        $env:BUILD_DIR = $(Get-Location).Path
        $env:PATH += ';' + $(Get-Location).Path + "\gams"
        $env:EXP = "test.pyomo -v --cat='nightly' pyomo " + $env:BUILD_DIR + "\pyomo-model-libraries"
        Invoke-Expression $env:EXP
