[files]
extend-exclude = ["*.eps"]

[default.extend-words]
# Ignore IDAES
IDAES = "IDAES"
idaes = "idaes"
# Ignore datas
Datas = "Datas"
datas = "datas"
# Ignore ND
ND = "ND"
nd = "nd"
# Ignore INOUT
inout = "inout"
INOUT= "INOUT"
# Add More Words Here

