name: Ubuntu no Py27

on:
  push:
    branches:
      - remove_py27_ga

jobs:
  pyomo-linux-tests:
    name: py${{ matrix.python-version }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo "Upgrade pip..."
        python -m pip install --upgrade pip
        echo "Install extras..."
        pip install numpy scipy ipython openpyxl sympy pyodbc pyyaml networkx xlrd matplotlib dill
        pip install pandas # Pandas needs to be installed after its dependencies to work correctly for Python 2.7 
        pip install seaborn pymysql pyro4 pint pathos 
        echo "Install GAMS..."
        wget -q https://d37drm4t2jghv5.cloudfront.net/distributions/24.8.5/linux/linux_x64_64_sfx.exe
        chmod +x linux_x64_64_sfx.exe
        ./linux_x64_64_sfx.exe -q -d gams
        PATH=$PATH:/gams/gams24.3_linux_x64_64_sfx
        echo "Clone Pyomo-model-libraries..."
        git clone --quiet https://github.com/Pyomo/pyomo-model-libraries.git
        echo "Install PyUtilib..."
        pip install --quiet git+https://github.com/PyUtilib/pyutilib
        echo "Install Pyomo..."
        python setup.py develop
    - name: Install extensions
      run: |
        echo "Download and install extensions..."
        pyomo download-extensions
        pyomo build-extensions
    - name: Run nightly tests with test.pyomo
      run: |
        echo "Run test.pyomo..."
        python -m pip install --upgrade pip
        pip install nose
        KEY_JOB=1
        test.pyomo -v --cat="nightly" pyomo `pwd`/pyomo-model-libraries