name: GitHub CI (unix)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pyomo-unix-tests:
    name: ${{ matrix.TARGET }}/py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
        - os: macos-latest
          TARGET: osx
        - os: ubuntu-latest
          TARGET: linux
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # Ensure cache directories exist
        mkdir -p ${GITHUB_WORKSPACE}/download-cache
        mkdir -p ${GITHUB_WORKSPACE}/pkg-cache
        if test "${{matrix.TARGET}}" == osx; then
            export HOMEBREW_CACHE=${GITHUB_WORKSPACE}/pkg-cache
            echo "Install pre-dependencies for pyodbc..."
            brew update
            brew list bash || brew install bash
            brew list gcc || brew install gcc
            brew link --overwrite gcc
            brew list pkg-config || brew install pkg-config
            brew list unixodbc || brew install unixodbc
            brew list freetds || brew install freetds
        fi
        echo ""
        echo "Upgrade pip..."
        echo ""
        python -m pip install --upgrade pip
        echo ""
        echo "Install Pyomo dependencies..."
        echo ""
        # Note: pandas 1.0.3 causes gams 29.1.0 import to fail in python 3.8
        pip install cython numpy scipy ipython openpyxl sympy pyyaml \
            pyodbc networkx xlrd pandas matplotlib dill seaborn pymysql \
            pyro4 pint pathos coverage nose
        echo ""
        echo "Install CPLEX Community Edition..."
        echo ""
        pip install cplex || echo "CPLEX Community Edition is not available for ${{ matrix.python-version }}"
        echo ""
        echo "Install BARON..."
        echo ""
        if [ ${{ matrix.TARGET }} == 'osx' ]; then
            wget -q https://www.minlp.com/downloads/xecs/baron/current/baron-osx64.zip -O baron_installer.zip
        else
            wget -q https://www.minlp.com/downloads/xecs/baron/current/baron-lin64.zip -O baron_installer.zip
        fi
        unzip -q baron_installer.zip
        mv baron-* baron-dir
        BARON_DIR=$(pwd)/baron-dir
        export PATH=$PATH:$BARON_DIR
        echo ""
        echo "Install IDAES Ipopt..."
        echo ""
        if [ ${{ matrix.TARGET }} == 'linux' ]; then
            sudo apt-get install libopenblas-dev gfortran liblapack-dev
            mkdir ipopt_solver && cd ipopt_solver
            wget -q https://github.com/IDAES/idaes-ext/releases/download/2.0.0/idaes-solvers-ubuntu1804-64.tar.gz -O ipopt.tar.gz
            tar -xzf ipopt.tar.gz
            cd ..
            export PATH=$PATH:$(pwd)/ipopt_solver
        fi
        echo ""
        echo "Install GJH_ASL_JSON..."
        echo ""
        wget -q "https://codeload.github.com/ghackebeil/gjh_asl_json/zip/master" -O gjh_asl_json.zip
        unzip -q gjh_asl_json.zip
        rm -rf gjh_asl_json.zip
        cd gjh_asl_json-master/Thirdparty
        ./get.ASL
        cd ..
        make
        export PATH=$PATH:$(pwd)/bin
        cd ..
        echo ""
        echo "Install GAMS..."
        echo ""
        GAMS_INSTALLER=${GITHUB_WORKSPACE}/download-cache/gams_installer.exe
        if test ! -e $GAMS_INSTALLER; then
            echo "...downloading GAMS"
            GAMS_URL=https://d37drm4t2jghv5.cloudfront.net/distributions/29.1.0
            if test "${{matrix.TARGET}}" == osx; then
                wget -q $GAMS_URL/macosx/osx_x64_64_sfx.exe -O $GAMS_INSTALLER
            else
                wget -q $GAMS_URL/linux/linux_x64_64_sfx.exe -O $GAMS_INSTALLER
            fi
            chmod +x $GAMS_INSTALLER
        fi
        chmod +x gams_installer.exe
        ./gams_installer.exe -q -d gams
        GAMS_DIR=`ls -d1 $(pwd)/gams/*/ | head -1`
        export PATH=$PATH:$GAMS_DIR
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GAMS_DIR
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$GAMS_DIR
        cd $GAMS_DIR/apifiles/Python/
        py_ver=$(python -c 'import sys;print("%s%s" % sys.version_info[:2])')
        gams_ver=api
        for ver in api_*; do
            if test ${ver:4} -le $py_ver; then
                gams_ver=$ver
            fi
        done
        cd $gams_ver
        python setup.py -q install -noCheck
        echo ""
        echo "Pass key environment variables to subsequent steps"
        echo ""
        echo "::set-env name=PATH::$PATH"
        echo "::set-env name=LD_LIBRARY_PATH::$LD_LIBRARY_PATH"
        echo "::set-env name=DYLD_LIBRARY_PATH::$DYLD_LIBRARY_PATH"

    - name: Install Pyomo and extensions
      run: |
        export PYTHONWARNINGS="ignore::UserWarning"
        echo ""
        echo "Clone Pyomo-model-libraries..."
        git clone --quiet https://github.com/Pyomo/pyomo-model-libraries.git
        echo ""
        echo "Install PyUtilib..."
        echo ""
        pip install --quiet git+https://github.com/PyUtilib/pyutilib
        echo ""
        echo "Install Pyomo..."
        echo ""
        python setup.py develop

    - name: Set up coverage tracking
      run: |
        COVERAGE_PROCESS_START=${GITHUB_WORKSPACE}/coveragerc
        echo "::set-env name=COVERAGE_PROCESS_START::$COVERAGE_PROCESS_START"
        cp ${GITHUB_WORKSPACE}/.coveragerc ${COVERAGE_PROCESS_START}
        echo "data_file=${GITHUB_WORKSPACE}/.coverage" \
            >> ${COVERAGE_PROCESS_START}
        SITE_PACKAGES=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
        echo 'import coverage; coverage.process_startup()' \
            > ${SITE_PACKAGES}/run_coverage_at_startup.pth

    - name: Download and install extensions
      run: |
        echo ""
        echo "Pyomo download-extensions"
        echo ""
        pyomo download-extensions
        echo ""
        echo "Pyomo build-extensions"
        echo ""
        pyomo build-extensions --parallel 2

    - name: Run Pyomo tests
      run: |
        echo "Run Pyomo tests..."
        test.pyomo -v --cat="nightly" pyomo `pwd`/pyomo-model-libraries

    - name: Upload coverage to codecov
      env:
        GITHUB_JOB_NAME: unix/${{matrix.TARGET}}/py${{matrix.python-version}}
      run: |
        coverage combine
        coverage report -i
        curl --retry 8 -s https://codecov.io/bash -o codecov.sh
        bash codecov.sh -X gcov -n "$GITHUB_JOB_NAME"
